// Generated by gencpp from file pose_graph_msgs/PoseGraph.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_MSGS_MESSAGE_POSEGRAPH_H
#define POSE_GRAPH_MSGS_MESSAGE_POSEGRAPH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pose_graph_msgs/PoseGraphNode.h>
#include <pose_graph_msgs/PoseGraphEdge.h>

namespace pose_graph_msgs
{
template <class ContainerAllocator>
struct PoseGraph_
{
  typedef PoseGraph_<ContainerAllocator> Type;

  PoseGraph_()
    : header()
    , nodes()
    , edges()  {
    }
  PoseGraph_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nodes(_alloc)
    , edges(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pose_graph_msgs::PoseGraphNode_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pose_graph_msgs::PoseGraphNode_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;

   typedef std::vector< ::pose_graph_msgs::PoseGraphEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pose_graph_msgs::PoseGraphEdge_<ContainerAllocator> >> _edges_type;
  _edges_type edges;





  typedef boost::shared_ptr< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> const> ConstPtr;

}; // struct PoseGraph_

typedef ::pose_graph_msgs::PoseGraph_<std::allocator<void> > PoseGraph;

typedef boost::shared_ptr< ::pose_graph_msgs::PoseGraph > PoseGraphPtr;
typedef boost::shared_ptr< ::pose_graph_msgs::PoseGraph const> PoseGraphConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_graph_msgs::PoseGraph_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_graph_msgs::PoseGraph_<ContainerAllocator1> & lhs, const ::pose_graph_msgs::PoseGraph_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nodes == rhs.nodes &&
    lhs.edges == rhs.edges;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_graph_msgs::PoseGraph_<ContainerAllocator1> & lhs, const ::pose_graph_msgs::PoseGraph_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_graph_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "483fdea4a5d26454e6dac91a4e5db16c";
  }

  static const char* value(const ::pose_graph_msgs::PoseGraph_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x483fdea4a5d26454ULL;
  static const uint64_t static_value2 = 0xe6dac91a4e5db16cULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_graph_msgs/PoseGraph";
  }

  static const char* value(const ::pose_graph_msgs::PoseGraph_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Graph nodes and edges.\n"
"PoseGraphNode[] nodes\n"
"PoseGraphEdge[] edges\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pose_graph_msgs/PoseGraphNode\n"
"Header header\n"
"\n"
"# Every pose has a unique key.\n"
"uint64 key\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: pose_graph_msgs/PoseGraphEdge\n"
"uint64 key_from\n"
"uint64 key_to\n"
;
  }

  static const char* value(const ::pose_graph_msgs::PoseGraph_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nodes);
      stream.next(m.edges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseGraph_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_graph_msgs::PoseGraph_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_graph_msgs::PoseGraph_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pose_graph_msgs::PoseGraphNode_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
    s << indent << "edges[]" << std::endl;
    for (size_t i = 0; i < v.edges.size(); ++i)
    {
      s << indent << "  edges[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pose_graph_msgs::PoseGraphEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.edges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_GRAPH_MSGS_MESSAGE_POSEGRAPH_H
